### ISSUE TITLE
Ship fixed samples to UW on Monday April 1 

### ISSUE THREAD

**Issue by AHuffmyer** [AHuffmyer/larval_symbiont_TPC#6]
Please package the three boxes in two gallon bags in the 4C fridge to send to Ariana via Fed Ex on Monday April 1 to arrive on or before Friday April 5th to UW. 

Ship to: 

Ariana Huffmyer, Roberts Lab 
University of Washington
1122 NE Boat St., Rm. 116
Seattle, WA 98105

Please add 1 or 2 ice packs into the package. Assign to CFS 500 2014 0000 0009814 for FedEx label. Thank you!

**Comment by JillAshey** [comment]
Expected delivery: Wednesday, April 3, 2024 by 5:00 PM
Tracking ID: 775767456240
Issue can be closed when package has been delivered.

**Comment by JillAshey** [comment]
Shipping information for Putnam lab filled out [here](https://docs.google.com/spreadsheets/d/1GpoxGAcQe1x9VUJexE63-xu7PABbwfz3Dqn8GOgvfUQ/edit?resourcekey#gid=352661747)

**Comment by AHuffmyer** [comment]
Received
