### ISSUE TITLE
KAPA bead clean up to remove primer dimers

### ISSUE THREAD

**Issue by AHuffmyer** [AHuffmyer/larval_symbiont_TPC#7]
We need to do a bead size selection clean up to remove primer dimers from our pooled PCR product for ITS2. Details of the amplification and prep for these samples are in my [notebook post](https://ahuffmyer.github.io/ASH_Putnam_Lab_Notebook/ITS2-amplicon-PCR-and-preparation-for-sequencing-20240326/). 

This is the protocol that we can use: https://elabdoc-prod.roche.com/eLD/api/downloads/88253649-670b-ee11-1c91-005056a772fd?countryIsoCode=pi. See protocol 2 starting on page 4 of this document for the protocol for amplicon clean up. 

Table 2 in the document linked above shows that a volume ratio of KAPA beads to sample is 1.5X to keep fragments >150bp. Our primer dimers are ~100bp and our target amplicon is >300bp. We therefore should use a 1.5X bead to sample volume ratio. 

We have ~70 uL total PCR product for each sample. We should subsample this pooled product for clean up by doing the clean up on 25 uL of PCR product and 37.5 uL of KAPA beads. This way we have more product to use if we have any problems with the clean up protocol.

We should have KAPA beads in the lab, but if not we could [place an order](https://elabdoc-prod.roche.com/eLD/web/pi/en/products/SEQ-KAPA-0161?searchTerm=07983271001&catalog=Researcher&orderBy=Relevance). 

@JillAshey could you please check that we have the necessary materials for this bead clean up protocol? 

After conducting clean up, we will need to run a new gel with a 1Kb and 100bp ladder to confirm primer dimers were removed. After that, we can label new strip tubes to deliver to Janet for sequencing. 

The next steps are: 

1. Bead clean up 
2. QC on gel 
3. Deliver to Janet for sequencing

**Comment by AHuffmyer** [comment]
We can also do the clean up on the positive control as a test before running the clean up on our experimental samples.

**Comment by AHuffmyer** [comment]
Draft protocol added here: https://github.com/AHuffmyer/ASH_Putnam_Lab_Notebook/blob/master/_posts/2024-04-01-KAPA-bead-clean-up-protocol-for-removal-of-primer-dimers-from-PCR-product.md. There are two outstanding questions I have about the protocol marked in the document. @JillAshey could you take a look and see what you think?

**Comment by hputnam** [comment]
Janet will still have to do the library prep PCR, quantification, normalization, pooling etc. I am not sure when the run will take place, but I will work with Janet on the logistics and finance end.

**Comment by hputnam** [comment]
Test Cleanup on the positive and negative control will give you helpful information as to what you can expect for all of the rest of the samples.

**Comment by AHuffmyer** [comment]
Thank you Hollie! Jill can prepare the PCR product and then we can deliver to Janet whenever it is convenient for her.

**Comment by JillAshey** [comment]
Ariana, are the samples still located in the -20C in the ITS2 box? And the positive control is in there as well?

**Comment by AHuffmyer** [comment]
Yes, all samples are in Freezer D (-20C), see in Row 54 on the sheet for Freezer D on the inventory here: https://docs.google.com/spreadsheets/d/1IMYmnNsN4D9cFbgLVdGKz67Albb3LxEyBh2GMtREMPU/edit#gid=817460189 

There is a pooled PCR product tube for every sample including the negative and positive controls.
